name: 'GameLib'
description: 'GameLib is a library plugin which helps in development for minecraft'
version: '${project.version}'
main: es.karmadev.gamelib.plugin.GamePlugin

author: KarmaDev

libraries:
  - 'com.google.inject.extensions:guice-assistedinject:7.0.0'
  - 'com.google.inject:guice:7.0.0'
  - 'org.bouncycastle:bcpkix-jdk18on:1.77'